name: ESLint

permissions:
  contents: read

on:
  push:
    branches: [main]

concurrency:
  group: eslint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          standalone: true

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Run pnpm install
        run: pnpm install --frozen-lockfile

      - name: Run astro sync
        run: pnpm run astro sync

      - name: Run Eslint
        env:
          ESLINT_PLUGIN_DIFF_COMMIT: ${{ env.BASE_REF }}
          GITHUB_TOKEN: ${{ github.token }}
        run: pnpm eslint .
