name: Astro Check

permissions:
  contents: read

on:
  push:
    branches: [main]

concurrency:
  group: astro-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  astro-check:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Run pnpm install
        run: pnpm install --frozen-lockfile

      - name: Run astro sync
        run: pnpm run astro sync

      - name: Run Astro Check
        run: pnpm run astro check
